services:
  - type: web
    name: backend
    env: node
    buildCommand: npx prisma migrate && npx prisma generate && prisma migrate deploy && npx prisma db push
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production